# Generated by Django 4.2.4 on 2023-11-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_business_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='custom_created_at_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
